### ISSUE TITLE
Change styleUrl file type to CSS in st-component

### ISSUE THREAD

**Issue by stefanreimers** [Fdom92/stencil-snippets#3]
As SASS is now outsourced to an Add-on to Stencil and not installed by default, the file ending of the `styleUrl` parameter should not be _.scss_ but _.css_ when defining a component. By now the `st-component` snippet creates _.scss_

**Comment by Fdom92** [comment]
Hi, thank you for the catch! 

I released a new version 2.1.2. This new version will generate the component with a css path for styleUrl.
