### ISSUE TITLE
1.0 component support

### ISSUE THREAD

**Issue by chimon2000** [Fdom92/stencil-snippets#5]
Stencil 1.0 changed so that the `jsxFactory` must be included when building components.   Thus the import for any component should now be 

```
import { Component, h } from "@stencil/core"
```

instead of 

```
import { Component } from "@stencil/core"
```

Which is what the snippet generates.

**Comment by Fdom92** [comment]
This PR #6 added the `h` on the import

**Comment by Fdom92** [comment]
Closing this ticket
